import com.liferay.portal.kernel.workflow.WorkflowStatusManagerUtil
import com.liferay.portal.kernel.workflow.WorkflowConstants

WorkflowStatusManagerUtil.updateStatus(WorkflowConstants.STATUS_INACTIVE, workflowContext)